{"errorMessage": "'SES' object has no attribute 'put_identity_dkim_attributes'", "errorType": "AttributeError", "requestId": "1b1de435-bf49-4d85-b63f-6ec49894b46c", "stackTrace": ["  File \"/var/task/index.py\", line 41, in lambda_handler\n    result = handle_phase_management(event, secret_arn, bucket_name)\n", "  File \"/var/task/index.py\", line 226, in handle_phase_management\n    phase_7_result = execute_phase_7(config, secret_arn, bucket_name)\n", "  File \"/var/task/index.py\", line 408, in execute_phase_7\n    response = ses_client.put_identity_dkim_attributes(\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 969, in __getattr__\n    raise AttributeError(\n"]}